language: python
python:
  - 3.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev
install:
  - pip install -r requirements.txt
before_script: true
script:
  - bin/enrichm
after_success: true
after_script: true